spring:
  application:
    name: ALOUTE_Thymeleaf
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/aloute}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Lak@2302}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect # Add this line for MySQL dialect
    show-sql: true
  mvc:
    servlet:
      load-on-startup: 1
